
@REM ilmerge /targetplatform:v4,c:\Windows\Microsoft.NET\Framework\v4.0.30319 /out:TestRun.exe "TestMain.exe" "Test.dll"
ilmerge /targetplatform:v4,c:\Windows\Microsoft.NET\Framework\v4.0.30319 /out:SharpDx.Reactive.dll SharpDX.dll SharpDX.Direct2D1.dll SharpDX.DXGI.dll Splat.dll System.Reactive.Core.dll System.Reactive.Interfaces.dll System.Reactive.Linq.dll System.Reactive.PlatformServices.dll System.Reactive.Windows.Threading.dll

@PAUSE

@REM C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe     /noconfig     /nowarn:1701,1702,2008     /nostdlib+     /platform:AnyCPU     /errorreport:prompt     /warn:4     /define:DEBUG;TRACE     /errorendlocation     /highentropyva-     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\Microsoft.CSharp.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\mscorlib.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.Core.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.Data.DataSetExtensions.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.Data.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.Xml.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.0\System.Xml.Linq.dll"     /debug+     /debug:full     /filealign:512     /optimize-     /out:obj\Debug\ReourceManUnMerged.exe     /resource:obj\Debug\ReourceManUnMerged.Properties.Resources.resources     /target:exe     /utf8output     Program.cs     Properties\AssemblyInfo.cs     Properties\Resources.Designer.cs     "C:\Users\mwrock\AppData\Local\Temp\.NETFramework, Version=v4.0.AssemblyAttributes.cs" (TaskId:26)
@REM When targeting 4.5 I get this:

@REM C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe     /noconfig     /nowarn:1701,1702,2008     /nostdlib+     /platform:AnyCPU     /errorreport:prompt     /warn:4     /define:DEBUG;TRACE     /errorendlocation     /highentropyva+     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\Microsoft.CSharp.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\mscorlib.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.Core.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.Data.DataSetExtensions.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.Data.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.Xml.dll"     /reference:"C:\Program Files\Reference Assemblies\Microsoft\Framework \.NETFramework\v4.5\System.Xml.Linq.dll"     /debug+     /debug:full     /filealign:512     /optimize-     /out:obj\Debug\ReourceManUnMerged.exe     /resource:obj\Debug\ReourceManUnMerged.Properties.Resources.resources     /target:exe     /utf8output     Program.cs     Properties\AssemblyInfo.cs     Properties\Resources.Designer.cs     "C:\Users\mwrock\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"     obj\Debug\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs     obj\Debug\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs (TaskId:21)
@REM http://www.hurryupandwait.io/blog/what-you-should-know-about-running-ilmerge-on-net-4-5-assemblies-targeting-net-4-0